name: 'Deploy static_content to S3'
on:
  push:
    branches:
      - master
#     paths:
#       - 'static_content/**'
env:
  bucketName: ${{ secrets.AWS_STATIC_CONTENT_BUCKET_NAME }}
#   cloudFrontDeploymentId: ${{ secrets.AWS_CLOUDFRONT_DEPLOYMENT_ID }}
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Deploy to AWS'
        run: |
          cp -a ../public/psc2ovm .
          aws s3 sync --acl public-read --delete . s3://${{ env.bucketName }}
        working-directory: 'static_content'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
